# Generated by Django 5.2.7 on 2025-10-04 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuscaSEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_sei', models.URLField(verbose_name='URL do SEI')),
                ('usuario_sei', models.CharField(max_length=100, verbose_name='Usuário SEI')),
                ('orgao', models.CharField(max_length=100, verbose_name='Órgão')),
                ('termos_pesquisa', models.TextField(verbose_name='Termos de Pesquisa')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Busca SEI',
                'verbose_name_plural': 'Buscas SEI',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Configuração')),
                ('url_sei', models.URLField(default='https://sei.economia.gov.br/', verbose_name='URL do SEI')),
                ('usuario_sei', models.CharField(max_length=100, verbose_name='Usuário SEI')),
                ('senha_sei_encriptada', models.CharField(max_length=255, verbose_name='Senha SEI (Encriptada)')),
                ('orgao', models.CharField(max_length=100, verbose_name='Órgão')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração SEI',
                'verbose_name_plural': 'Configurações SEI',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoSEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=100, verbose_name='Número do Processo')),
                ('nome_documento', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('unidade', models.CharField(blank=True, max_length=200, verbose_name='Unidade')),
                ('usuario_inclusao', models.CharField(blank=True, max_length=100, verbose_name='Usuário de Inclusão')),
                ('data_inclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Inclusão')),
                ('link_original', models.URLField(max_length=500, verbose_name='Link Original')),
                ('link_curto', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Curto')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos_sei/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('busca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='sei_automation.buscasei')),
            ],
            options={
                'verbose_name': 'Documento SEI',
                'verbose_name_plural': 'Documentos SEI',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['numero_processo'], name='sei_automat_numero__f4a7cf_idx'), models.Index(fields=['nome_documento'], name='sei_automat_nome_do_373888_idx')],
            },
        ),
    ]
